# Generated by Django 4.2.30 on 2026-05-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
